version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: yarn --no-progress --frozen-lockfile
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: yarn test
